### ISSUE TITLE
Bug: Белый экран при операциях в кошельке

### ISSUE THREAD

**Issue by allfory0u** [golos-blockchain/golos-ui#104]
Белый экран при переходе на страницу "[Награда за курирование](https://golos.id/@allforyou/curation-rewards)" со страницы "[Кошелек](https://golos.id/@allforyou/transfers)".

---
![image](https://user-images.githubusercontent.com/17462020/84572870-a654b600-ada5-11ea-8a77-8b02cf7884f6.png)

---

`TypeError: "e.split is not a function"
    value https://golos.id/assets/app.a52e160e001d5cebee0f.js:1
    value https://golos.id/assets/app.a52e160e001d5cebee0f.js:1
    Ci https://golos.id/assets/14.a52e160e001d5cebee0f.js:143
    Ii https://golos.id/assets/14.a52e160e001d5cebee0f.js:143
    ha https://golos.id/assets/14.a52e160e001d5cebee0f.js:143
    pa https://golos.id/assets/14.a52e160e001d5cebee0f.js:143
    Ga https://golos.id/assets/14.a52e160e001d5cebee0f.js:143
    Wa https://golos.id/assets/14.a52e160e001d5cebee0f.js:143
    Va https://golos.id/assets/14.a52e160e001d5cebee0f.js:143
    es https://golos.id/assets/14.a52e160e001d5cebee0f.js:143
    jn https://golos.id/assets/14.a52e160e001d5cebee0f.js:143
14.a52e160e001d5cebee0f.js:143:71989
    Bi https://golos.id/assets/14.a52e160e001d5cebee0f.js:143
    callback https://golos.id/assets/14.a52e160e001d5cebee0f.js:143
    Ho https://golos.id/assets/14.a52e160e001d5cebee0f.js:143
    Vo https://golos.id/assets/14.a52e160e001d5cebee0f.js:143
    Za https://golos.id/assets/14.a52e160e001d5cebee0f.js:143
    Ga https://golos.id/assets/14.a52e160e001d5cebee0f.js:143
    Wa https://golos.id/assets/14.a52e160e001d5cebee0f.js:143
    Va https://golos.id/assets/14.a52e160e001d5cebee0f.js:143
    es https://golos.id/assets/14.a52e160e001d5cebee0f.js:143
    jn https://golos.id/assets/14.a52e160e001d5cebee0f.js:143`

---

Windows 10 & Firefox 77.0.1

**Comment by allfory0u** [comment]
Update: после перехода их "Кошелька" на страницу "Авторские награды", а затем на "Кураторские награды" проблема повторилась еще 1 раз. Но больше "белый экран не появлялся".

**Comment by Lex-Ai** [comment]
Аналогичный баг порой возникает при переходе на страницу полученных донатов https://golos.id/@lex/donates-to и возникал при переходе на https://golos.id/workers (до момента как добавили на ссылку костыль в виде target=_blank).

**Comment by Lex-Ai** [comment]
При операции Пополнить TIP-баланс с CLAIM-баланса "белый экран"

![2020-07-05_154821](https://user-images.githubusercontent.com/12001684/86533146-98dba900-bed7-11ea-8146-60ccf173e3a4.jpg)

аналогично и при увеличении СГ c CLAIM-баланса, увеличении СГ с ликвидного баланса

**Comment by Lex-Ai** [comment]
https://github.com/golos-blockchain/golos-ui/commit/025920c10de2eb93cac9f9e00218fec6c6a36250
