### ISSUE TITLE
Bug: кнопка "обновить" неактивна после смены суммы для кнопок вознаграждения

### ISSUE THREAD

**Issue by allfory0u** [golos-blockchain/golos-ui#154]
В настройках можно менять стандартные значения сумм для кнопки вознаграждения, но после любых изменений кнопка "Обновить" не становится активной, чтобы можно было сохранить их.

![](https://recordit.co/c0v6PV8Xrt.gif)

**Comment by Lex-Ai** [comment]
Она и не должна для этих полей, сохраняются сразу

**Comment by allfory0u** [comment]
> 
> 
> Она и не должна для этих полей, сохраняются сразу (добавлю пояснения).

Я так и думал, тогда нужно добавить какое-нибудь всплывающее окно, что эти изменения сохранены, так как рядовой пользователь просто не поймет, что они сохранились.
