### ISSUE TITLE
Не скрывать список делегатов после установки прокси

### ISSUE THREAD

**Issue by allfory0u** [golos-blockchain/golos-ui#155]
После установки прокси пропадает список делегатов и его невозможно увидеть. После обновления страницы он на долю с секунды появляется и продает.

![](https://recordit.co/IIxcLz9Ute.gif)

**Comment by Lex-Ai** [comment]
Так и задумано, добавил прокси, выбор делегатов делает кто-то другой, так и на Стиме

**Comment by allfory0u** [comment]
> Так и задумано, добавил прокси, выбор делегатов делает кто-то другой, так и на Стиме

Выбор делает кто-то другой, да, но зачем от пользователя весь список с технической информацией про делегатов скрывать? Это выглядит просто, как костыль, вместо того, чтобы после установки прокси убрать кнопки для голосования за делегатов. Если я доверил свой голос другому аккаунту это ведь не значит, что я совсем не хочу следить за ситуацией.

**Comment by Lex-Ai** [comment]
Ну давай я верну в список, но делать заявку на это я не буду. 
Это мелочь, а править там прилично...

**Comment by Lex-Ai** [comment]
https://github.com/golos-blockchain/golos-ui/commit/0e929450cfabc338c112e6da01efde67e72ac84c
