### ISSUE TITLE
Предотвращение показа спама/флуда

### ISSUE THREAD

**Issue by bitfag** [golos-blockchain/golos-ui#18]
1. Простой способ. Автоматически не показывать контент от аккаунтов с репой меньше N
2. Более сложный способ. Показывать только контент, запощенный через морду. Со стороны сервера генерируется авторизационный токен который включается в транзакцию на стороне клиента. Все кто хочет сделать posting (клиент или сторонний скрипт) запрашивают токен у сервера и включают его в json_metadata. А морда по некоей своей логике либо выдаёт токен, либо отказывает.

**Comment by t3ran13** [comment]
1 можно сделать уже сейчас
2. Слишком сложно, не говоря о том что придется создавать новый сервис который можно будет за досить ... В общем рассадник проблем)

**Comment by bitfag** [comment]
1. Тут только проблема что можно скриптом отловить первый пост новичка и сразу хуйнуть флагом, нужен доп. алгоритм чтобы позволял им повисеть какое-то время.

**Comment by kedgaks** [comment]
1. еще проблема в том что репу спамеру могут пытаться "накручивать" с другого аккуанта,
повышать до необходимой

**Comment by t3ran13** [comment]
1. Ну так отрицательная репа ведь тоже не ноль. Можно начинать хидать если репа мееьше -Х, эквивалент флага на 100к сг и более

**Comment by Lex-Ai** [comment]
Сейчас при отрицательной репутации акка все скрывает (посты/комменты), вопрос по ботам что уже набрали ее прилично...

**Comment by bitfag** [comment]
@Lex-Ai много где писал, решается написанием микросервиса который внутри считает репу, а морда его запрашивает. Внутри такого микросервиса алгоритм можно постоянно дорабатывать итеративно. Это гораздо гибче чем что-то пробовать менять в ноде.

**Comment by t3ran13** [comment]
Ну это банальный блек лист клиента
