### ISSUE TITLE
Реализация правок в интерфейсе с появ. системы донатов

### ISSUE THREAD

**Issue by Lex-Ai** [golos-blockchain/golos-ui#20]
С реализацией системы донатов в БЧ описанной тут https://github.com/golos-blockchain/golos/issues/83 потребуются ряд правок в интерфейсе клиента.

# Донаты

Посмотрев пример как это было сделано на https://whaleshares.io/@whaleshares/rewarding-others-with-tips

1. Нужно добавить под постами кнопку доната в виде **привлекающего** значка/гифки

![2020-02-22_194610](https://user-images.githubusercontent.com/12001684/75096013-067fdc00-55ac-11ea-827b-dfae4a0280bb.jpg)

либо обыграть и сделать что-то вроде "кнопки во всю ширину", напр.

![111](https://user-images.githubusercontent.com/12001684/81606089-1bb21d00-93db-11ea-993b-02db77ab2e66.png)

2. Перенести информацию о кол-ве голосов (зачеркнуто на скрине выше) в место между кнопкой лайк/дизлайк (как описано в комменте https://github.com/golos-blockchain/golos-ui/issues/20#issuecomment-591534197 или как на скрине выше).

3. При нажатии отблагодарить/доната нужно выпадающее меню с пресетами/шкалой выбора суммы/окном для коммента, желательно, с каким-то "эффектом" после доната. Пример с Whaleshares:

![2](https://user-images.githubusercontent.com/12001684/74245942-d9524480-4cf4-11ea-967b-6dd55403946d.gif)

4. Перенести красную кнопку "Отблагодарить" под постами с **сохр. её функциональности** (перевод ликвидных токенов с основного баланса отправителя на баланс получателя) в окошко об авторе, в стиле кнопок как там. И обозвать "Перевод" (чтобы не путали с донатной "отблагодарить").

![222](https://user-images.githubusercontent.com/12001684/80419619-243a2c00-88e2-11ea-8e6a-36965fa49901.jpg)

5. Заменить "вывод суммы" от апвоутов на сумму полученных донатов, при нажатии на которую будет возможность увидеть **список донатящих и суммы** (с сорт. от большего к меньшему, как было на апвоутах).

![81611052-18229400-93e3-11ea-89f9-d504c967dfd1](https://user-images.githubusercontent.com/12001684/82612270-1cad3080-9bcb-11ea-92a3-8a4eb3a5d0d0.jpg)

6. Добавить возможность доната комментов (доб. ссылку Отблагодарить перед Ответить).

7. Добавить возможность доната автору - кнопка Отблагодарить в профиле, напр. тут

![74108361-89576e80-4b8a-11ea-93fd-c76415fe74d6](https://user-images.githubusercontent.com/12001684/75090916-d539e880-5578-11ea-90e5-a786a982ef98.jpg)

# Информация о донатах

Список отправленных и полученных пользователем донатов, в отличии от Whaleshares:

![3](https://user-images.githubusercontent.com/12001684/73095142-0203cd00-3ef3-11ea-9fc8-d271e36e7ff3.jpg)

1. Вероятно стоит разместить как отдельные странички в меню Награды профиля юзера

![6](https://user-images.githubusercontent.com/12001684/73095216-22338c00-3ef3-11ea-9215-781a19c457cb.jpg)

2. **Не забыв как-то обозначить** в списке донатов (или выводить их на отдельной странице "Доход от рефералов"), полученные % от донатов в адрес привлеченных рефералов. Чтобы реферер наглядно видел какой из его рефералов "успешен" на проекте...

# Страница кошелька

1. В выпадающее меню баланса ликвидных токенов ГОЛОС добавить опцию "**Передать на TIP-баланс**"

![8](https://user-images.githubusercontent.com/12001684/73095489-c87f9180-3ef3-11ea-9435-456b0a8aebf2.jpg)

2. Выше "текущих" балансов добавить отображение двух новых: **TIP-баланс** и **CLAIM-баланс**

**"TIP-баланс"**, с которого возможно отправить токены в пополнение СГ (добавить в его меню опцию "Увеличить Силу Голоса" + желательно опцию "Отблагодарить" с отправкой доната на TIP-баланс другого пользователя).

> Описание серым: 
> Баланс с которого вы вознаграждаете других пользователей, и на который получаете вознаграждения сами. Токены с него вывести можно только в пополнение Силы Голоса.

**"CLAIM-баланс"**, который в БЧ `accumulative_balance` (добавить в его выпадающее меню **claim**-операции: "Пополнить TIP-баланс" и "Увеличить Силу Голоса"). 

> Описание серым: 
> Баланс вашей доли от общей эмиссии токенов блокчейна Голос, которую вы можете востребовать для пополнения TIP-баланса, либо увеличения Силы Голоса. 

3. Как-то отображать в строке CLAIM-баланса время до окончания/начала след. цикла (ведь делегаты могут поменять срок `claim_idleness_time`), пример с Whaleshares ниже (желательно добавить и какой-то "эффект" после клэйма):

![4](https://user-images.githubusercontent.com/12001684/74246490-a65c8080-4cf5-11ea-9fe4-96de7da09f76.gif)

4. Убрать блок оценочной стоимости аккаунта

![111](https://user-images.githubusercontent.com/12001684/80321848-3b691300-8829-11ea-965a-22552952976f.png)

# Остальное

1. Добавить ленту "Донаты" по типу имеющейся "Популярное" (только с сортировкой постов по сумме полученных к ним донатов).

![2020-02-09_222740](https://user-images.githubusercontent.com/12001684/74108430-7abd8700-4b8b-11ea-8aa6-88fa7a0a52ad.jpg)

2. Добавить поля для новых дел. параметров `claim_idleness_time` и `min_invite_balance` на стр. https://golos.id/@XXX/witness (в UI - `\components\modules\WitnessProps.jsx`)

3. Желательно добавить в профиль раздел "Статистика" (что на скрине Топы)

![73095216-22338c00-3ef3-11ea-9215-781a19c457cb](https://user-images.githubusercontent.com/12001684/75090986-948e9f00-5579-11ea-9c8e-6cce15ee2edb.jpg)

- с страницей топ-100 пользователей и сорт. по сумме отправленных ими донатов (**Топ донатов**), что-то вроде https://dpos.space/golos-donates/ напр. за последний месяц

- если возможно, страницу топ-100 комментариев с сорт. по сумме полученных на них донатов (**Топ комментариев**), напр. за последний месяц

**Comment by 0n0t0le** [comment]
Предлагаю между кнопками не соотношение отображать +17 / -3 а аля как на Яндух Зене в комментариях - отображать значение, которое набрало наибольшее число голосов (если Голосов ЗА, то например зеленым цветом (или синим, если у нас такой стиль), если Голосов Против, то красным цветом). А уже при клике на данном значении будет всплывать попап с соотношением и списком проголосовавших юзеров

**Comment by 0n0t0le** [comment]
> Перенести красную кнопку "Отблагодарить" под постами с сохр. её функциональности (перевод ликвидных токенов с основного баланса отправителя на баланс получателя) в окошко об авторе, в стиле кнопок как там:

Тут вопрос: если я хочу отблагодарить автора за конкретный пост/комментарий ликвидным переводом (как сейчас), то как мне быть?  Вариант "просто отблагодарить за то что он такой хороший мне не подходит"

**Comment by 0n0t0le** [comment]
> 
> 
> > Перенести красную кнопку "Отблагодарить" под постами с сохр. её функциональности (перевод ликвидных токенов с основного баланса отправителя на баланс получателя) в окошко об авторе, в стиле кнопок как там:
> 
> Тут вопрос: если я хочу отблагодарить автора за конкретный пост/комментарий ликвидным переводом (как сейчас), то как мне быть? Вариант "просто отблагодарить за то что он такой хороший мне не подходит"

Ну и развивая этот же вопрос (я уже затрагивал его ранее в чатах). Хотелось бы чтобы донаты через механику Типс-донат суммировались на клиенте с донатами через механику трансфер (ссылка на пост) и отображались единой суммой под постом.

**Comment by Lex-Ai** [comment]
> Тут вопрос: если я хочу отблагодарить автора за конкретный пост/комментарий ликвидным переводом (как сейчас), то как мне быть? Вариант "просто отблагодарить за то что он такой хороший мне не подходит"

Я рассуждаю просто, если функция не масс., он может нажав кнопку отблагодарить там куда она будет перенесена и внести адрес коммента в мемо (так как адрес поста вносится по умолчанию если мемо не заполнено). Делать систему вкладок во всплывающем окне доната под постом или комментом и смешивать операцию по постинг-ключу (донат) и операцию по актив-ключу (трансфер ликвида), имхо не норм.

**Comment by 0n0t0le** [comment]
> Добавить возможность доната комментов (ссылка Отблагодарить).

Надо бы не плодить сущности, в плане названий для одного и того же действия. Под постом кнопка судя по скрину называется "ОТПРАВИТЬ ВОЗНАГРАЖДЕНИЕ", а в остальных местах "Отблагодарить".

**Comment by Lex-Ai** [comment]
> Ну и развивая этот же вопрос (я уже затрагивал его ранее в чатах). Хотелось бы чтобы донаты через механику Типс-донат суммировались на клиенте с донатами через механику трансфер (ссылка на пост) и отображались единой суммой под постом.

С этим та же петрушка, механика типс-донатов в БЧ, с отдельным АПИ под статистику/рейтинг, а трансферы на custom_json (значит нужен отдельный обработчик операций). Уточню конечно, можно ли что-то сделать...

**Comment by 0n0t0le** [comment]
> 
> 
> > Тут вопрос: если я хочу отблагодарить автора за конкретный пост/комментарий ликвидным переводом (как сейчас), то как мне быть? Вариант "просто отблагодарить за то что он такой хороший мне не подходит"
> 
> @0n0t0le Я рассуждаю просто, если функция не масс., он может нажав кнопку отблагодарить там куда она будет перенесена и внести адрес коммента в мемо (так как адрес поста вносится по умолчанию если мемо не заполнено). Делать систему вкладок во всплывающем окне доната под постом или комментом и смешивать операцию по постинг-ключу (донат) и операцию по актив-ключу (трансфер ликвида), имхо не норм.

а кто решил масс это функция или не масс? Для масс адопшна в перспективе на клиентах должны появится встроенные шлюзы с возможностью **донатить любую сумму в любой валюте/криптовалюте ликвидом на лету (с мгновенной конвертацией во внутреннюю единую валюту Голоса - не уверен что именно GLS)**. Ибо если я прочитал интересный пост, и только что зарегался на Голосе для того чтобы задонатить понравившемуся автору, то **последнее** что я сделаю это куплю себе кучу Голосов, заведу все в СГ, подожду 2 мес (делая клейм каждый день), пока на типс балансе накопится сумма достойная данного автора, и сделаю наконец донат.

**Comment by 0n0t0le** [comment]
> 
> 
> > > Тут вопрос: если я хочу отблагодарить автора за конкретный пост/комментарий ликвидным переводом (как сейчас), то как мне быть? Вариант "просто отблагодарить за то что он такой хороший мне не подходит"
> > 
> > 
> > @0n0t0le Я рассуждаю просто, если функция не масс., он может нажав кнопку отблагодарить там куда она будет перенесена и внести адрес коммента в мемо (так как адрес поста вносится по умолчанию если мемо не заполнено). Делать систему вкладок во всплывающем окне доната под постом или комментом и смешивать операцию по постинг-ключу (донат) и операцию по актив-ключу (трансфер ликвида), имхо не норм.
> 
> а кто решил масс это функция или не масс? Для масс адопшна в перспективе на клиентах должны появится встроенные шлюзы с возможностью **донатить любую сумму в любой валюте/криптовалюте ликвидом на лету (с мгновенной конвертацией во внутреннюю единую валюту Голоса - не уверен что именно GLS)**. Ибо если я прочитал интересный пост, и только что зарегался на Голосе для того чтобы задонатить понравившемуся автору, то **последнее** что я сделаю это куплю себе кучу Голосов, заведу все в СГ, подожду 2 мес (делая клейм каждый день), пока на типс балансе накопится сумма достойная данного автора, и сделаю наконец донат.

для того чтобы в будущем это стало возможно нужно продумать базис уже сейчас, а базис - это возможность выбора при нажатии на кнопку "Отблагодарить" в какой форме я хочу отблагодарить (в типсовой или ликвидной)

**Comment by 0n0t0le** [comment]
> 
> 
> > Добавить возможность доната комментов (ссылка Отблагодарить).
> 
> Надо бы не плодить сущности, в плане названий для одного и того же действия. Под постом кнопка судя по скрину называется "ОТПРАВИТЬ ВОЗНАГРАЖДЕНИЕ", а в остальных местах "Отблагодарить". Отблагодарить короче и удобнее ...

И да у комментов ведь тоже будет отображаться сумма донатов? Отдельно для каждого коммента? что будет отображаться на месте суммы донатов коммента, если за коммент не донатили? Что если коммент наберет больше донатов чем сам пост? Как будут ранжироваться комментарии под постом (по числу апвоутов/даунвоутов или по сумме донатов). Будет ли топ по донатам на комментариях?

**Comment by Lex-Ai** [comment]
> > > Добавить возможность доната комментов (ссылка Отблагодарить).
> > 
> > 
> > Надо бы не плодить сущности, в плане названий для одного и того же действия. Под постом кнопка судя по скрину называется "ОТПРАВИТЬ ВОЗНАГРАЖДЕНИЕ", а в остальных местах "Отблагодарить". Отблагодарить короче и удобнее ...
> 
> И да у комментов ведь тоже будет отображаться сумма донатов? Отдельно для каждого коммента? что будет отображаться на месте суммы донатов коммента, если за коммент не донатили? Что если коммент наберет больше донатов чем сам пост? Как будут ранжироваться комментарии под постом (по числу апвоутов/даунвоутов или по сумме донатов). Будет ли топ по донатам на комментариях?

Да, у комментов тоже будет сумма донатов. Если донатов не было, скорее всего как и прежде, будет отображаться 0,00 GOLOS. Комментарии как и посты во всех лентах кроме ленты "Донаты" ранжируются по апвоутам/даунвоутам. Топ по донатам комментов под вопросом, зависит от того будет ли АПИ, станет ясно с софтфорком для АПИ-нод.
