### ISSUE TITLE
Многоуровневое правое меню

### ISSUE THREAD

**Issue by serdrdoor** [golos-blockchain/golos-ui#26]
1. Меню которое появляется при клике на аккаунт
![image](https://user-images.githubusercontent.com/11815105/73655369-f2c51200-469e-11ea-96fd-5af081277961.png)

2. Меню, которое появляется при клике правее предыдущего по вертикальному троеточию:

![image](https://user-images.githubusercontent.com/11815105/73655421-16885800-469f-11ea-821a-793916f9ad5c.png)

(в него предлагаю добавить иконки - а то выглядит как будто про них забыли)

Иконки интуитивно сокращают время на поиск, не нужно вчитываться, что более юзерфрендли.

**Comment by Lex-Ai** [comment]
https://github.com/golos-blockchain/golos-ui/commit/853aaf3aedeb20996fcd45d154a70cbe2dd27be6
