### ISSUE TITLE
Bug: golos-btn btn-secondary btn-round

### ISSUE THREAD

**Issue by Kwaskoff** [golos-blockchain/golos-ui#27]
Open URL https://golos.id/workers
Push button "golos-btn btn-secondary btn-round"
Cannot read property 'post' of undefined

![Imgur](https://i.imgur.com/0YhVi3E.png)

Firefox/Chromium

**Comment by Lex-Ai** [comment]
Нужно скрывать кнопку "Показать ещё", пока кол-во заявок не больше 10...
На примере выше только одна заявка, и кнопка "путает" пользователей.

**Comment by Lex-Ai** [comment]
Объединено с ишью https://github.com/golos-blockchain/golos-ui/issues/40
