### ISSUE TITLE
Плитки предыдущих постов автора

### ISSUE THREAD

**Issue by erikkartmen** [golos-blockchain/golos-ui#28]
Заметил, что многие авторы пишут посты частями, а-ля главы рассказов или этапы какого-либо действия. Почему бы не сделать внизу листа поста плитки (превью) предыдущих постов, что бы не надо было переходить в блог пользователя и искать предыдущие посты по данной теме.

**Comment by avral** [comment]
@erikkartmen Хорошая идея, есть пример того где это реализовано?

**Comment by erikkartmen** [comment]
> @erikkartmen Хорошая идея, есть пример того где это реализовано?

Да в том же Дзене есть такое. Просто в пост подтягивать последние посты в виде превьюшек

**Comment by Lex-Ai** [comment]
например так, брать три поста по такому же тегу от автора
если их нет, выводить популярные по тегу посты других авторов

![ишью плитки 1](https://user-images.githubusercontent.com/12001684/84922899-2e50fd80-b0cf-11ea-8186-5b61ba6ec33d.jpg)

**Comment by Lex-Ai** [comment]
в идеале при открытии поста не в модальном окне (там то понятно это сложно), сделать еще один плавающий блок, с популярными статьями по такому же тегу сбоку от поста

что-то вроде 

![ишью плитки 2](https://user-images.githubusercontent.com/12001684/84923203-956eb200-b0cf-11ea-90e5-cd086a20fbe1.jpg)
