### ISSUE TITLE
Заменить image hosting, рассмотреть IFPS/BTFS

### ISSUE THREAD

**Issue by Kwaskoff** [golos-blockchain/golos-ui#29]
settings -> upload Profile picture
result
https://images.golos.io/DQmbc9ZG454NVMgpZhQN3b1kFUTPSHjzvaT9xc1onZ35PmD/photo_2020-02-06_21-34-10.jpg
change to another image hosting (self or public)
Thx

**Comment by Lex-Ai** [comment]
Поддерживаю, полагаю стоит перейти полностью на какой-то один image host

Пока наверно и steemitimages
А может и сразу рассмотреть IFPS решения, 

https://www.bittorrent.com/btfs/ тут вариант интеграции в Smoke -
https://www.dropbox.com/s/p4kkqhdo5ht89in/smoke_btfs.pdf?dl=0

Возможно ещё стоит добавить в исключения кешерования *.imgur.com, *.fbcdn.net (фейсбук) *.userapi.com (вконтакте), а то кеширующий сервис режет фотки (либо в модалке увеличения открывать фото напрямую с источника, а не кеширующего)...
