### ISSUE TITLE
Предложения по доработке интерфейса воркеров

### ISSUE THREAD

**Issue by 0n0t0le** [golos-blockchain/golos-ui#72]
Запуск механики Воркеров на Голосе, это отличный шаг, но сам интерфейс воркеров (очевидно делался просто для того чтобы был) в плане юзабилити, и донесения до пользователя нужной информации оставляет желать лучшего. Так как Воркеры - одна из основных механик для дальнейшего развития Голоса, как платформы, думаю есть смысл сделать раздел воркеров более юзер-френдли для того, чтобы его было проще использовать как самим воркерам, так и пользователям, которые за них голосуют.

Ниже будет приведен пример того, как можно изменить основной раздел со списком рабочих предложений.

![](https://i.postimg.cc/QdGJjBvS/WPS.png)
Название заявки (ссылка на подробное описание) вынести в заголовок, шрифт можно сделать крупнее, при этом освободится куча места для основной информации. Статус можно убрать, т.к. у нас выбран подраздел "Открытые заявки", а в нем могут находиться только заявки, по которым в данный момент идет голосование. Точно также можно просматривать "Успешные заявки" и "Отклоненные заявки".

> Не совсем понятна суть статусов Выплачиваемые и Закрытые заявки, выплата ведь происходит моментально после истечения времени заявки, а в закрытых у нас и успешные и отклоненные и отмененные...

Столбец Автор уходит в строку с заголовком, и располагается в правой части. Из сведений на данной странице остаются только запрашиваемая сумма, количество дней до окончания голосования и значение по кворуму (с указанием какое минимальное значение СГ необходимо достигнуть - по идее надо тянуть с БЧ), в случае если необходимый порог преодолен значение можно писать зеленым, если не преодолен, то красным. Оставшееся место занимает линейчатая диаграмма, отображающая процентное соотношение веса Голосов отданных ЗА предложение к Голосам, отданным ПРОТИВ предложения. И фактические значения в СГ + количество проголосовавших ЗА и ПРОТИВ. В правой нижней части указана дата публикации заявки. 
***

Кроме страницы просмотра списка заявок, нужно также переработать всплывающее окно с подробным просмотр конкретной заявки и голосованием

![](https://i.postimg.cc/3whkvbvC/work.png)

Сейчас при просмотре заявки отображается **Процент проголосовавших от общей СГ**, но не отображается пороговый процент, необходимый для достижения кворума (устанавливаемый медианой делегатов). Пусть я например проверил, что сейчас этот процент составляет 15%, но многие то об этом не знают (тем более он может быть изменен), и визуально в заявке (например последней от VVK) не видно что ему не хватало каких то долей процента для того чтобы пройти порог. Кроме того в заявке отображается например что собрано 14%, нужно отображать значение с двумя знаками после запятой, т.к. 14,01% далеко не тоже самое что 14,94%.

Текущий процент проголосовавшей СГ  14,01 / 15%

 Кроме изменения в отображении значений предлагаю добавить прогрессбар с отображением расчетной суммы выплаты по отношению к максимальной запрошенной сумме выплаты. 

Кроме того кнопки **ЗА (21) / ПРОТИВ (0)** никак не ассоциируются с тем, что на них нужно нажать для того, чтобы Проголосовать за/против конкретной заявки. Скорее нажав на них ты просто ожидаешь увидеть тех, кто уже проголосовал ЗА. Кроме того имеющегося интерактива не достаточно для того, чтобы сделать вывод о том, что ты проголосовал, да кнопка вроде бы становится активной (при этом счетчик проголосовавших не меняется). Но выделение кнопки как активной не является достоверным подтверждением того, что Голосование произошло. 

**Можно реализовать голосование в следующем виде:**

Два чекбокса (единовременно может быть выбран только один)
* За
* Против
 поле с выбором процента Голоса(как сейчас) и кнопка **Голосовать** (не активна пока не выбран один из чекбоксов). После того, как пользователь проголосовал мы отображаем ему сообщение типа "Спасибо за участие, ваш голос учтен бла бла бла". 

Либо две кнопки со значком
* Голосовать За (палец вверх)
* Голосовать Против (палец вниз)
И при голосовании тоже нужен интерактивчик. 

### Еще вопросы по интерфейсу

Сейчас если Голосуешь против, даже имея приличный стек - твоего аккаунта не видно в списке проголосовавших (если их больше 20)

Не понятно, зачем нужна кнопка **Показать все**, если в данный конкретный момент отображаются все возможные заявки (нет скрытых)

Желаемая сумма можно изменить на `запрашиваемая` (requested) сумма

Также отсутствует возможность дать прямую ссылку на голосование по конкретному воркеру, что негативно влияет на возможность продвижения заявки. 
***
P.S. Кстати всплывающее окно с просмотром заявки и Голосованием можно сделать более полноценной страницей, отображать описание воркера из поста прямо на ней на вкладке описание (а ссылка на пост будет для комментирования), и прочую расширенную статистику по голосованию. Нужно обсудить, если что можно дополнить данное предложение

**Comment by Lex-Ai** [comment]
Многое было описано здесь https://github.com/golos-blockchain/golos-ui/issues/40
и возможный воркер упустит либо что-то то, либо что-то тут )

**Comment by 0n0t0le** [comment]
> 
> 
> Многое было описано здесь #40
> и возможный воркер упустит либо что-то то, либо что-то тут )
> 
> Имхо стоит добавить комментом чего не хватает к той заявке, либо редакнуть эту оставив только "новые" предложения, чтобы воркер "обработал" их обе не путаясь. Или добавить в твою из той, а её закрою.

хорошо, скомпоную все в одну заявку

**Comment by Lex-Ai** [comment]
> > Многое было описано здесь #40
> > и возможный воркер упустит либо что-то то, либо что-то тут )
> > Имхо стоит добавить комментом чего не хватает к той заявке, либо редакнуть эту оставив только "новые" предложения, чтобы воркер "обработал" их обе не путаясь. Или добавить в твою из той, а её закрою.
> 
> хорошо, скомпоную все в одну заявку

Отл., а ту удалим.

**Comment by bitfag** [comment]
Что ещё хотелось бы. Допустим, пользователь заходит на клиент, происходит проверка - есть ли активные заявки воркеров, если есть, проверяется, проголосовал ли пользователь. Если не проголосовал, показывать плашку "Есть активные рабочие предложения, пожалуйста проголосуйте".

Считаю, что это может повысить вовлечённость пользователей в говернанс.

**Comment by Lex-Ai** [comment]
> Не совсем понятна суть статусов Выплачиваемые и Закрытые заявки, выплата ведь происходит моментально после истечения времени заявки, а в закрытых у нас и успешные и отклоненные и отмененные...

Да, закрытые это все что были завершены. А выплачиваемые появятся в том случае если фонд воркеров не был бы таким "богатым" и при одобренной заявке не хватало (выплаты будут каждые 10 минут до полной оплаты).
